const OPENFGA_URL = 'http://localhost:8080';
const CHECK_ITERATIONS = 500;
const LIST_OBJECTS_ITERATIONS = 50;
const DOCUMENT_COUNT = 100;
const TEST_RUNS = 10;
const BATCH_SIZE = 50;
const CONCURRENCY = 20;

module.exports = {
  OPENFGA_URL,
  CHECK_ITERATIONS,
  LIST_OBJECTS_ITERATIONS,
  DOCUMENT_COUNT,
  TEST_RUNS,
  BATCH_SIZE,
  CONCURRENCY
};